// Generated by CoffeeScript 1.10.0
(function() {
  var Item, List, list_view, template,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Item = (function(superClass) {
    extend(Item, superClass);

    function Item() {
      return Item.__super__.constructor.apply(this, arguments);
    }

    Item.prototype.defaults = {
      title: "",
      completed: false,
      id: null
    };

    return Item;

  })(Backbone.Model);

  List = (function(superClass) {
    extend(List, superClass);

    function List() {
      return List.__super__.constructor.apply(this, arguments);
    }

    List.prototype.model = Item;

    return List;

  })(Backbone.Collection);

  template = function(input) {
    return "<li> " + input + " <button class='delete'>X</button> </li>";
  };

  window.ItemView = (function(superClass) {
    extend(ItemView, superClass);

    function ItemView() {
      return ItemView.__super__.constructor.apply(this, arguments);
    }

    ItemView.prototype.initialize = function() {
      return this.model = new Item;
    };

    ItemView.prototype.render = function() {
      var input;
      input = this.model.get('title');
      $(this.el).append(template(input));
      return this;
    };

    ItemView.prototype.removeItem = function() {
      this.model.destroy();
      this.remove();
      return console.log("item removed");
    };

    return ItemView;

  })(Backbone.View);

  window.ListView = (function(superClass) {
    extend(ListView, superClass);

    function ListView() {
      return ListView.__super__.constructor.apply(this, arguments);
    }

    ListView.prototype.el = $('body');

    ListView.prototype.events = {
      "click .add": "appendItem",
      "keydown": "keyPress",
      "click .delete": "deleteItem"
    };

    ListView.prototype.initialize = function() {
      this.list = new List;
      return this.render();
    };

    ListView.prototype.render = function() {
      $(this.el).html("<div id='app'></div>");
      $("#app").append("<input type='text' /><br />");
      $("#app").append("<button class='add'>Add Item</button>");
      $('#app').append("<ul id='list'></ul>");
      return this;
    };

    ListView.prototype.appendItem = function() {
      var input, item;
      console.log("button pressed");
      input = $('input').val();
      item = new ItemView({
        el: "#list"
      });
      item.model.set({
        title: input
      });
      this.list.add(item.model);
      return item.render();
    };

    ListView.prototype.keyPress = function(e) {
      if (e.which === 13) {
        return this.appendItem();
      }
    };

    return ListView;

  })(Backbone.View);

  list_view = new ListView;

}).call(this);
